[phases.setup]
nixPkgs = ["python3", "python3Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python -c 'import matplotlib; matplotlib.font_manager._rebuild()'"]

[start]
cmd = "python main.py"